import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from "@/_components/Footer/Footer";
import Navbar from "@/_components/Navbar/Navbar";
import { ToastContainer } from "react-toastify";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="mx-auto px-3 py-2 sm:px-6 sm:py-4 sm:max-w-xl md:max-w-2xl lg:max-w-4xl xl:max-w-6xl overflow-x-hidden">
          <Navbar />
          {children}
          <Footer></Footer>
        </div>
        <ToastContainer position="bottom-right" />
      </body>
    </html>
  );
}
